export * from "./boardActions";
export * from "./listActions";
export * from "./cardActions";
export const CONSTANTS = {
    ADD_LIST:"ADD_LIST",
    MOVE_LIST:"MOVE_LIST",
    DELETE_LIST:"DELETE_LIST",
    CHANGE_LIST_TITLE:"CHANGE_LIST_TITLE",
    DELETE_LIST_BY_ID:"DELETE_LIST_BY_ID",
    MOVE_CARD:"MOVE_CARD",
    ADD_CARD:"ADD_CARD",
    DELETE_CARD:"DELETE_CARD",
    CHANGE_CARD_TEXT:"CHANGE_CARD_TEXT",
    DELETE_CARD:"DELETE_CARD",
    DELETE_LIST_BY_CARD_ID:"DELETE_LIST_BY_CARD_ID"
};